// Frontend/ProjectSvelte/src/game-page/game-board/players/PlayerTechnologyTile.svelte
<script lang="ts">
	import type { TechnologyTileDto } from "$dto/interfaces";
	import { interactiveElementClass } from "$utils/miscellanea";
	import { InteractiveElementType } from "$utils/types";
	import { isNil, noop } from "lodash";
	import { get } from "svelte/store";
	import { getGamePageContext } from "../../GamePage.context";
	import { deriveOwnAdvancedTileInteractionState, deriveOwnStandardTileInteractionState } from "../../store/selectors";
	import ActionToken from "../ActionToken.svelte";
	import AdvancedTechnologyTile from "../AdvancedTechnologyTile.svelte";
	import StandardTechnologyTile from "../StandardTechnologyTile.svelte";

	export let tile: TechnologyTileDto;
	export let playerId: string;

	const { store, activeWorkflow } = getGamePageContext();

	let clickable = false;
	let selected = false;
	let tileClicked = noop;
	$: {
		const covered = !isNil(tile.coveredByAdvancedTile);
		const tileId = covered ? tile.coveredByAdvancedTile! : tile.id;
		const selector = covered
			? deriveOwnAdvancedTileInteractionState(tile.coveredByAdvancedTile!)
			: deriveOwnStandardTileInteractionState(tile.id);
		const interactionState = selector(store, playerId);
		const state = get(interactionState);
		clickable = state.clickable;
		selected = state.selected;
		tileClicked = clickable
			? () => {
					$activeWorkflow?.elementSelected(
						tileId,
						covered ? InteractiveElementType.OwnAdvancedTile : InteractiveElementType.OwnStandardTile
					);
			  }
			: noop;
	}
</script>

<div class="player-technology-tile w-full relative" class:interactive={clickable || selected}>
	<StandardTechnologyTile type={tile.id} />
	{#if tile.coveredByAdvancedTile}
		<div class="advanced-tile absolute">
			<AdvancedTechnologyTile type={tile.coveredByAdvancedTile} />
			<div class="action-token advanced">
				{#if tile.used}
					<ActionToken />
				{/if}
			</div>
		</div>
	{:else}
		<div class="action-token advanced">
			{#if tile.used}
				<ActionToken />
			{/if}
		</div>
	{/if}
	<div class={interactiveElementClass(clickable, selected)} style:pointer-events="all" on:click|stopPropagation={tileClicked} />
</div>

<style>
	.player-technology-tile:not(.interactive):hover .advanced-tile {
		transform: rotateX(90deg);
		transition: transform 250ms;
	}

	.advanced-tile {
		width: 82.5%;
		top: 8%;
		left: 5%;
	}

	.action-token {
		position: absolute;
		width: 50%;
		top: 20%;
		left: 25%;
	}

	.action-token.advanced {
		width: 64%;
		top: 5%;
		left: 10%;
	}
</style>

// Frontend/Portal/src/game-page/game-board/player-area/PlayerTechnologyTile.tsx
import createStyles from "@mui/styles/createStyles";
import makeStyles from "@mui/styles/makeStyles";
import { isNil, partialRight } from "lodash";
import { observer } from "mobx-react";
import { MouseEvent } from "react";
import { TechnologyTileDto } from "../../../dto/interfaces";
import { interactiveElementClass } from "../../../utils/miscellanea";
import { useGamePageContext } from "../../GamePage.context";
import { selectOwnAdvancedTileInteractionState, selectOwnStandardTileInteractionState } from "../../store/selectors";
import { useWorkflow } from "../../WorkflowContext";
import { InteractiveElementType } from "../../workflows/enums";
import ActionToken from "../ActionToken";
import AdvancedTechnologyTile from "../AdvancedTechnologyTile";
import StandardTechnologyTile from "../StandardTechnologyTile";

interface PlayerTechnologyTileProps {
	tile: TechnologyTileDto;
	playerId: string;
}

const useStyles = makeStyles(() =>
	createStyles({
		root: {
			width: "100%",
			position: "relative",
			"& .advanced-tile": {
				position: "absolute",
				width: "82.5%",
				top: "8%",
				left: "5%",
			},
			"&:not(.interactive):hover .advanced-tile": {
				transform: "rotateX(90deg)",
				transition: "transform 250ms",
			},
		},
		actionToken: {
			position: "absolute",
			width: "50%",
			top: "17%",
			left: "25%",
			"&.advanced": {
				width: "64%",
				top: "5%",
				left: "10%",
			},
		},
	})
);

const PlayerTechnologyTile = ({ tile, playerId }: PlayerTechnologyTileProps) => {
	const classes = useStyles();
	const { vm } = useGamePageContext();
	const covered = !isNil(tile.coveredByAdvancedTile);
	const tileId = covered ? tile.coveredByAdvancedTile! : tile.id;
	const selector = covered ? selectOwnAdvancedTileInteractionState(tile.coveredByAdvancedTile!) : selectOwnStandardTileInteractionState(tile.id);
	const { isClickable, isSelected } = partialRight(selector, playerId)(vm);
	const { activeWorkflow } = useWorkflow();
	const tileClicked = (evt: MouseEvent) => {
		evt.stopPropagation();
		if (!isClickable) {
			return;
		}
		activeWorkflow?.elementSelected(tileId, covered ? InteractiveElementType.OwnAdvancedTile : InteractiveElementType.OwnStandardTile);
	};

	return (
		<div className={classes.root + (isClickable || isSelected ? " interactive" : "")}>
			<StandardTechnologyTile type={tile.id} />
			{!covered && <div className={classes.actionToken}>{tile.used && <ActionToken />}</div>}
			{covered && (
				<div className="advanced-tile">
					<AdvancedTechnologyTile type={tile.coveredByAdvancedTile!} />
					<div className={classes.actionToken + " advanced"}>{tile.used && <ActionToken />}</div>
				</div>
			)}
			<div className={interactiveElementClass(isClickable, isSelected)} style={{ pointerEvents: "all" }} onClick={tileClicked}></div>
		</div>
	);
};

export default observer(PlayerTechnologyTile);
