// Frontend/Portal/src/game-page/game-board/PlayerMarker.tsx
import { Theme } from "@mui/material/styles";
import createStyles from '@mui/styles/createStyles';
import makeStyles from '@mui/styles/makeStyles';
import { Race } from "../../dto/enums";
import { withAspectRatioW } from "../../utils/miscellanea";
import { getRaceColor } from "../../utils/race-utils";

interface PlayerMarkerProps {
	race: Race;
	shape?: "circle" | "octagon";
}

const useStyles = makeStyles((theme: Theme) =>
	createStyles({
		root: {
			...withAspectRatioW(1),
			width: "calc(100% + 2px)",
			borderRadius: "50%",
			border: ({ race }: PlayerMarkerProps) => `1px solid ${theme.palette.getContrastText(getRaceColor(race))}`,
			backgroundColor: ({ race }: PlayerMarkerProps) => getRaceColor(race),
		},
	})
);

const PlayerMarker = (props: PlayerMarkerProps) => {
	const classes = useStyles(props);
	return <div className={classes.root}></div>;
};

export default PlayerMarker;

// Frontend/ProjectSvelte/src/game-page/game-board/PlayerMarker.svelte
<script lang="ts">
	import type { Race } from "$dto/enums";
	import { getContrastColor } from "$utils/colors";
	import { withAspectRatioW } from "$utils/miscellanea";
	import { getRaceColor } from "$utils/race-utils";

	export let race: Race;
	export let shape: "circle" | "octagon" = "circle";

	let style = "";
	$: {
		const raceColor = getRaceColor(race);
		style = `
	${withAspectRatioW(1)};
	background-color: ${raceColor};
	border-color: ${getContrastColor(raceColor)}
	`;
	}
</script>

<div class="player-marker" {style} />

<style>
	.player-marker {
		width: calc(100% + 2px) !important;
		border: 1px solid;
		border-radius: 50%;
	}
</style>
