// Frontend/ProjectSvelte/src/game-page/game-board/scoring-board/FederationTokenStack.svelte
<script lang="ts" context="module">
	const HEIGHT_TO_WIDTH_RATIO = 1.05;
</script>

<script lang="ts">
	import type { FederationTokenStackDto } from "$dto/interfaces";
	import { interactiveElementClass, withAspectRatioW } from "$utils/miscellanea";
	import { InteractiveElementType } from "$utils/types";
	import { noop, range } from "lodash";
	import { getGamePageContext } from "../../GamePage.context";
	import { deriveFederationTokenStackInteractionState } from "../../store/selectors";
	import FederationToken from "../FederationToken.svelte";

	export let stack: FederationTokenStackDto;

	const { store, activeWorkflow } = getGamePageContext();
	const interactionState = deriveFederationTokenStackInteractionState(stack.type)(store);
	$: ({ clickable, selected } = $interactionState);
	$: stackClicked = clickable
		? () => {
				$activeWorkflow?.elementSelected(stack.type, InteractiveElementType.FederationToken);
		  }
		: noop;
</script>

<div style={withAspectRatioW(1 / HEIGHT_TO_WIDTH_RATIO)}>
	<div class="wh-full absolute top-0 left-0">
		{#each range(0, stack.remaining) as n}
			<div class="token" style={`top: ${n * 12}%; left: ${n * 15}%`}>
				<FederationToken type={stack.type} />
			</div>
		{/each}
	</div>
	<div class={interactiveElementClass(clickable, selected)} on:click={stackClicked} />
</div>

<style>
	.token {
		position: absolute;
		width: 70%;
	}
</style>

// Frontend/Portal/src/game-page/game-board/federation-token/FederationTokenStack.tsx
import createStyles from "@mui/styles/createStyles";
import makeStyles from "@mui/styles/makeStyles";
import { noop, range } from "lodash";
import { observer } from "mobx-react";
import { FederationTokenStackDto } from "../../../dto/interfaces";
import { fillParentAbs, interactiveBorder, interactiveElementClass, withAspectRatioW } from "../../../utils/miscellanea";
import { useGamePageContext } from "../../GamePage.context";
import { selectFederationTokenStackInteractionState } from "../../store/selectors";
import { useWorkflow } from "../../WorkflowContext";
import { InteractiveElementType } from "../../workflows/enums";
import FederationToken from "./FederationToken";

const HEIGHT_TO_WIDTH_RATIO = 1.05;

interface FederationTokenStackProps {
	stack: FederationTokenStackDto;
}

const useStyles = makeStyles(() =>
	createStyles({
		root: {
			...withAspectRatioW(1 / HEIGHT_TO_WIDTH_RATIO),
			...interactiveBorder,
		},
		wrapper: {
			...fillParentAbs,
		},
		token: {
			position: "absolute",
			width: "100%",
		},
	})
);

const FederationTokenStack = ({ stack }: FederationTokenStackProps) => {
	const classes = useStyles();
	const { vm } = useGamePageContext();
	const { isClickable, isSelected } = selectFederationTokenStackInteractionState(stack.type)(vm);
	const { activeWorkflow } = useWorkflow();
	const tokenClicked = isClickable
		? () => {
				activeWorkflow?.elementSelected(stack.type, InteractiveElementType.FederationToken);
		  }
		: noop;

	return (
		<div className={classes.root}>
			<div className={classes.wrapper}>
				{range(0, stack.remaining).map(n => (
					<div key={n} className={classes.token} style={{ width: "70%", top: `${n * 12}%`, left: `${n * 15}%` }}>
						<FederationToken type={stack.type} />
					</div>
				))}
			</div>
			<div className={interactiveElementClass(isClickable, isSelected)} onClick={tokenClicked}></div>
		</div>
	);
};

export default observer(FederationTokenStack);
