// Frontend/Portal/src/game-page/logs/GameLog.tsx
import ListItem from "@mui/material/ListItem";
import ListItemText from "@mui/material/ListItemText";
import { GameLogDto } from "../../dto/interfaces";
import styles from "./GameLog.module.scss";
import PlayerLog from "./PlayerLog";

interface SystemLogProps {
	message: string;
}

const SystemLog = ({ message }: SystemLogProps) => {
	return (
		<ListItem className={styles.systemLog}>
			<ListItemText primary={message} primaryTypographyProps={{ className: "gaia-font text-center" }} />
		</ListItem>
	);
};

interface GameLogProps {
	log: GameLogDto;
	canRollback: boolean;
	doRollback(actionId: number): void;
}

const GameLog = ({ log, canRollback, doRollback }: GameLogProps) =>
	log.isSystem ? <SystemLog message={log.message} /> : <PlayerLog log={log} canRollback={canRollback} doRollback={doRollback} />;

export default GameLog;

// Frontend/ProjectSvelte/src/game-page/logs/GameLog.svelte
<script lang="ts">
	import type { GameLogDto } from "$dto/interfaces";
	import PlayerLog from "./PlayerLog.svelte";
	import SystemLog from "./SystemLog.svelte";

	export let log: GameLogDto;
	export let canRollback: boolean;
	export let doRollback: (actionId: number) => void;
</script>

{#if log.isSystem}
	<SystemLog message={log.message} />
{:else}
	<PlayerLog {log} {canRollback} {doRollback} />
{/if}
