// Frontend/ProjectSvelte/src/game-page/desktop/DesktopView.svelte
<script lang="ts" context="module">
	import { ActiveView } from "$utils/types";

	const PLAYER_AREA_WIDTH_TO_HEIGHT_RATIO = 1.439;
	const ACTIVATABLE_VIEWS = [
		{ label: "Map", view: ActiveView.Map },
		{ label: "Research Board", view: ActiveView.ResearchBoard },
		{ label: "Scoring Board", view: ActiveView.ScoringBoard },
	];
</script>

<script lang="ts">
	import { GamePhase } from "$dto/enums";
	import type { GameStateDto, PlayerInGameDto } from "$dto/interfaces";
	import { noop } from "lodash";
	import { onMount } from "svelte";
	import PlayerArea from "../game-board/players/PlayerArea.svelte";
	import PlayerBox from "../game-board/players/PlayerBox.svelte";
	import ResearchBoard from "../game-board/research-board/ResearchBoard.svelte";
	import ScoringBoard from "../game-board/scoring-board/ScoringBoard.svelte";
	import GameLog from "../logs/GameLog.svelte";
	import MainView from "./MainView.svelte";
	import { getGamePageContext } from "../GamePage.context";

	export let currentPlayerId = "";
	export let isSpectator = false;

	const { store } = getGamePageContext();

	$: game = $store.game;
	$: players = game.players;
	$: isGameCreator = game.createdBy.id === currentPlayerId;
	$: canRollback = isGameCreator && game.currentPhase === GamePhase.Rounds;
	$: activeView = $store.activeView;
	$: actualView = activeView === ActiveView.Map || activeView === ActiveView.PlayerArea ? ActiveView.Map : activeView;
	$: {
		if (activeView !== ActiveView.PlayerArea) {
			hidePlayerArea();
		} else {
			showPlayerArea(currentPlayerId);
		}
	}

	//#region Sizing

	let container: HTMLDivElement;
	let width: number;
	let height: number;
	let playerAreaModalStyle = `width: 0; height: 0; top: 0; left: 0;`;

	const calculatePlayerAreaModalSize = () => {
		width = container.clientWidth;
		height = container.clientHeight;

		let dpaHeight = height * 0.95;
		let dpaWidth = dpaHeight * PLAYER_AREA_WIDTH_TO_HEIGHT_RATIO;
		if (dpaWidth > width) {
			dpaWidth = width * 0.95;
			dpaHeight = dpaWidth / PLAYER_AREA_WIDTH_TO_HEIGHT_RATIO;
		}

		playerAreaModalStyle = `width: ${dpaWidth}px; height: ${dpaHeight}px; top: ${(height - dpaHeight) / 2}px; left: ${
			(width - dpaWidth) / 2
		}px;`;
	};

	onMount(calculatePlayerAreaModalSize);

	//#endregion

	let playerAreaToShow: PlayerInGameDto | null = null;

	const setActiveView = (view: ActiveView) => {
		store.update(gamePageStore => ({
			...gamePageStore,
			activeView: view,
		}));
	};

	const showPlayerArea = (playerId: string) => {
		if (playerId === playerAreaToShow?.id) {
			hidePlayerArea();
			return;
		}

		const player = players.find(p => p.id === playerId)!;
		playerAreaToShow = player;
	};
	const hidePlayerArea = () => {
		playerAreaToShow = null;
	};
</script>

<svelte:window on:resize={calculatePlayerAreaModalSize} />
<div class="desktop-view wh-full overflow-x-hidden overflow-y-auto">
	<div class="grid grid-cols-4 gap-2 h-full">
		<div class="col-span-3 h-full flex flex-col gap-2">
			<div class="flex justify-center items-center flex-auto relative" bind:this={container}>
				{#if actualView === ActiveView.Map}
					<MainView {game} {width} {height} showMinimaps={true} minimapClicked={noop} />
				{:else if actualView === ActiveView.ResearchBoard}
					<ResearchBoard board={game.boardState.researchBoard} {width} {height} />
				{:else if actualView === ActiveView.ScoringBoard}
					<ScoringBoard
						board={game.boardState.scoringBoard}
						roundBoosters={game.boardState.availableRoundBoosters}
						federationTokens={game.boardState.availableFederations}
						isMobile={false}
					/>
				{:else if actualView === ActiveView.NotesAndSettings}
					<!-- <PlayerConfig gameId={game.id} /> -->
				{/if}
				{#if playerAreaToShow}
					<div class="absolute z-10 bg-gray-900" style={playerAreaModalStyle}>
						<PlayerArea player={playerAreaToShow} framed />
					</div>
				{/if}
			</div>
			<div class="tabs flex items-center justify-center gap-4 flex-shrink-0 bg-white">
				{#each ACTIVATABLE_VIEWS as av (av.view)}
					<div
						class="tab text-center text-gray-900 cursor-pointer gaia-font"
						class:active={actualView === av.view}
						on:click={() => setActiveView(av.view)}
					>
						{av.label}
					</div>
				{/each}
			</div>
		</div>
		<div class="h-full overflow-x-hidden overflow-y-auto">
			<div class="w-full flex flex-col gap-2">
				{#each game.players as player, index (player.id)}
					<div class="contents" on:click={() => showPlayerArea(player.id)}>
						<PlayerBox {player} {index} />
					</div>
				{/each}
			</div>
			<div class="w-full mt-2 flex flex-col gap-2">
				{#each game.gameLogs as log}
					<GameLog {log} {canRollback} doRollback={noop} />
				{/each}
			</div>
		</div>
	</div>
</div>

<style>
	.tabs {
		height: 40px;
	}

	.tab {
		border-bottom: 0 solid black;
	}

	.tab.active {
		border-bottom-width: 3px;
	}
</style>

// Frontend/Portal/src/game-page/desktop-view/DesktopView.tsx
import { Grid, Tab, Tabs } from "@mui/material";
import { isNil } from "lodash";
import { observer } from "mobx-react";
import { useEffect, useLayoutEffect, useRef, useState } from "react";
import { GamePhase } from "../../dto/enums";
import { PlayerInGameDto } from "../../dto/interfaces";
import { ElementSize } from "../../utils/hooks";
import { Nullable } from "../../utils/miscellanea";
import PlayerConfig from "../config/PlayerConfig";
import PlayerArea from "../game-board/player-area/PlayerArea";
import PlayerBox from "../game-board/player-box/PlayerBox";
import ResearchBoard from "../game-board/research-board/ResearchBoard";
import ScoringBoard from "../game-board/scoring-board/ScoringBoard";
import { GameViewProps } from "../GamePage";
import { useGamePageContext } from "../GamePage.context";
import GameLog from "../logs/GameLog";
import MainView from "../main-view/MainView";
import { ActiveView } from "../workflows/types";
import useStyles from "./desktop-view.styles";

const PLAYER_AREA_WIDTH_TO_HEIGHT_RATIO = 1.439;

const DesktopView = ({ game, players, activeView, currentPlayerId, isSpectator }: GameViewProps) => {
	const classes = useStyles();
	const { vm } = useGamePageContext();
	const activeViewContainerRef = useRef<HTMLDivElement>(null);
	const [activeViewDimensions, setActiveViewDimensions] = useState<Nullable<ElementSize>>(null);
	const isGameCreator = game.createdBy.id === currentPlayerId;
	const canRollback = isGameCreator && game.currentPhase === GamePhase.Rounds;

	const [playerAreaToShow, setPlayerAreaToShow] = useState<Nullable<PlayerInGameDto>>(null);
	const showPlayerArea = (playerId: string) => {
		if (playerId === playerAreaToShow?.id) {
			hidePlayerArea();
			return;
		}
		const player = players.find(p => p.id === playerId)!;
		setPlayerAreaToShow(player);
	};
	const hidePlayerArea = () => {
		setPlayerAreaToShow(null);
	};
	useEffect(() => {
		if (activeView !== ActiveView.PlayerArea) {
			hidePlayerArea();
			return;
		}
		showPlayerArea(currentPlayerId);
	}, [activeView]);

	useLayoutEffect(() => {
		if (isNil(activeViewContainerRef.current)) {
			return;
		}

		setActiveViewDimensions({
			width: activeViewContainerRef.current.offsetWidth,
			height: activeViewContainerRef.current.offsetHeight,
		});
	}, [activeViewContainerRef, game]);

	const dialogPlayerAreaDimensions = {
		width: 0,
		height: 0,
		top: 0,
		left: 0,
	};
	if (!isNil(activeViewDimensions)) {
		let dpaHeight = activeViewDimensions.height * 0.95;
		let dpaWidth = dpaHeight * PLAYER_AREA_WIDTH_TO_HEIGHT_RATIO;
		if (dpaWidth > activeViewDimensions.width) {
			dpaWidth = activeViewDimensions.width * 0.95;
			dpaHeight = dpaWidth / PLAYER_AREA_WIDTH_TO_HEIGHT_RATIO;
		}
		dialogPlayerAreaDimensions.width = dpaWidth;
		dialogPlayerAreaDimensions.height = dpaHeight;
		dialogPlayerAreaDimensions.top = (activeViewDimensions.height - dpaHeight) / 2;
		dialogPlayerAreaDimensions.left = (activeViewDimensions.width - dpaWidth) / 2;
	}

	const PlayerBoxesAndLogs = (
		<div className={classes.playerBoxesAndLogs}>
			{players.map((p, index) => (
				<div key={p.id} className={classes.playerBox} onClick={() => showPlayerArea(p.id)}>
					<PlayerBox player={p} index={index + 1} />
				</div>
			))}
			{[...game.gameLogs].reverse().map((log, index) => (
				<div key={index} className={classes.gameLog}>
					<GameLog log={log} canRollback={canRollback} doRollback={actionId => vm.rollbackGameAtAction(game.id, actionId)} />
				</div>
			))}
		</div>
	);

	const actualView = activeView === ActiveView.Map || activeView === ActiveView.PlayerArea ? ActiveView.Map : activeView;

	return (
		<Grid container className={classes.root}>
			<Grid item className={classes.boardArea} xs={12} md={9}>
				<div ref={activeViewContainerRef} className={classes.activeViewContainer}>
					{actualView === ActiveView.Map && activeViewDimensions && (
						<MainView
							game={game}
							width={activeViewDimensions.width}
							height={activeViewDimensions.height}
							showMinimaps={true}
							minimapClicked={view => vm.setActiveView(view)}
						/>
					)}
					{actualView === ActiveView.ResearchBoard && activeViewDimensions && (
						<ResearchBoard board={game.boardState.researchBoard} width={activeViewDimensions.width} height={activeViewDimensions.height} />
					)}
					{actualView === ActiveView.ScoringBoard && (
						<ScoringBoard
							board={game.boardState.scoringBoard}
							roundBoosters={game.boardState.availableRoundBoosters}
							federationTokens={game.boardState.availableFederations}
							isMobile={false}
						/>
					)}
					{actualView === ActiveView.NotesAndSettings && <PlayerConfig gameId={game.id} />}
					{!isNil(playerAreaToShow) && (
						<div
							className={classes.hoveredPlayerArea}
							style={{
								width: dialogPlayerAreaDimensions.width,
								height: dialogPlayerAreaDimensions.height,
								left: dialogPlayerAreaDimensions.left,
								top: dialogPlayerAreaDimensions.top,
							}}
						>
							<PlayerArea player={playerAreaToShow} framed={true} />
						</div>
					)}
				</div>
				<Tabs className={classes.tabs} value={actualView} onChange={(__, val: ActiveView) => vm.setActiveView(val)} indicatorColor="primary" variant={"standard"} centered>
					<Tab className="gaia-font" label="Map" value={ActiveView.Map} />
					<Tab className="gaia-font" label="Research" value={ActiveView.ResearchBoard} />
					<Tab className="gaia-font" label="Scoring" value={ActiveView.ScoringBoard} />
					<Tab className="gaia-font" label="Notes" value={ActiveView.NotesAndSettings} />
				</Tabs>
			</Grid>
			<Grid item className={classes.controlArea} xs={12} md={3}>
				{PlayerBoxesAndLogs}
			</Grid>
		</Grid>
	);
};

export default observer(DesktopView);
