// Frontend/ProjectSvelte/src/game-page/dialogs/auction/AuctionedRace.svelte
<script lang="ts">
	import type { Race } from "$dto/enums";
	import type { AuctionDto } from "$dto/interfaces";
	import { getContrastColor } from "$utils/colors";
	import { assetUrl } from "$utils/miscellanea";
	import { getRaceColor, getRaceImage, getRaceName } from "$utils/race-utils";

	export let auction: AuctionDto;
	export let selected: boolean;
	export let onSelected: (r: Race) => void;

	$: race = auction.race;
	$: raceName = getRaceName(race);
	$: background = getRaceColor(race);
	$: color = getContrastColor(background);
	$: username = auction.playerUsername;
</script>

<div class="flex flex-col items-center" on:click={() => onSelected(race)}>
	<h6 class="gaia-font">
		{raceName}
	</h6>
	<div class="p-1 relative" style={`background-color: ${background}; color: ${color};`}>
		<ion-avatar>
			<img src={assetUrl(`Races/${getRaceImage(race)}`)} alt={raceName} />
		</ion-avatar>
		{#if selected}
			<div class="absolute -bottom-1 right-0">
				<ion-checkbox checked={true} />
			</div>
		{/if}
	</div>
	{#if username}
		<div class="flex flex-col items-center mt-1 gaia-font">
			<p>
				{username}
			</p>
			<p>
				{`${auction.points} VP`}
			</p>
		</div>
	{/if}
</div>

// Frontend/Portal/src/game-page/dialogs/auction/AuctionedRace.tsx
import { useTheme } from "@mui/material";
import Avatar from "@mui/material/Avatar";
import Typography from "@mui/material/Typography";
import CheckBoxRounded from "@mui/icons-material/CheckBoxRounded";
import { Race } from "../../../dto/enums";
import { AuctionDto } from "../../../dto/interfaces";
import { useAssetUrl } from "../../../utils/hooks";
import { getRaceColor, getRaceImage, getRaceName } from "../../../utils/race-utils";
import useStyles from "./auctioned-race.styles";

interface AuctionedRaceProps {
	auction: AuctionDto;
	selected: boolean;
	onSelected(race: Race): void;
}

const AuctionedRace = ({ auction, selected, onSelected }: AuctionedRaceProps) => {
	const theme = useTheme();
	const classes = useStyles();
	const race = auction.race;
	const imgUrl = useAssetUrl(`Races/${getRaceImage(race)}`);
	const background = getRaceColor(race);
	const color = theme.palette.getContrastText(background);
	return (
		<div className={classes.root} onClick={() => onSelected(race)}>
			<Typography variant="h6" className="gaia-font">
				{getRaceName(auction.race)}
			</Typography>
			<div className={classes.raceImage} style={{ backgroundColor: background, color }}>
				<Avatar src={imgUrl} />
				{selected && (
					<div className="check">
						<CheckBoxRounded />
					</div>
				)}
			</div>
			{auction.playerUsername && (
				<div className={classes.playerInfo}>
					<Typography variant="caption" className="gaia-font">
						{auction.playerUsername}
					</Typography>
					<Typography variant="caption" className="gaia-font">
						{`${auction.points} VP`}
					</Typography>
				</div>
			)}
		</div>
	);
};

export default AuctionedRace;
