// Frontend/Portal/src/game-page/status-bar/StatusBar.tsx
import Button from "@mui/material/Button";
import Menu from "@mui/material/Menu";
import MenuItem from "@mui/material/MenuItem";
import { Theme } from "@mui/material/styles";
import Typography from "@mui/material/Typography";
import createStyles from "@mui/styles/createStyles";
import makeStyles from "@mui/styles/makeStyles";
import { observer } from "mobx-react";
import { useState } from "react";
import { AvailableActionDto, GameStateDto } from "../../dto/interfaces";
import { centeredFlexRow, fillParent, Nullable } from "../../utils/miscellanea";
import { useGamePageContext } from "../GamePage.context";
import { selectAvailableActions, selectAvailableCommands, selectStatusMessage } from "../store/selectors";
import { useWorkflow } from "../WorkflowContext";
import { Command } from "../workflows/types";
import { fromAction } from "../workflows/utils";

const useStyles = makeStyles((theme: Theme) =>
	createStyles({
		root: {
			...centeredFlexRow,
			flexDirection: ({ useVerticalLayout }: { useVerticalLayout: boolean }) => (useVerticalLayout ? "column" : "row"),
			...fillParent,
			padding: theme.spacing(1, 2),
			[theme.breakpoints.down("md")]: {
				padding: theme.spacing(0.5, 1),
			},
			backgroundColor: "white",
			boxShadow: "0 3px 3px 3px rgba(0, 0, 0, 0.5)",
		},
		message: {
			flex: "0 1 auto",
			color: "black",
			fontSize: "0.9rem",
			textAlign: "center",
			[theme.breakpoints.down("md")]: {
				fontSize: "0.7rem",
			},
			[theme.breakpoints.down("sm")]: {
				fontSize: "0.6rem",
			},
		},
		actionSelector: {
			flex: "0 0 auto",
			marginLeft: theme.spacing(2),
			[theme.breakpoints.down("md")]: {
				marginLeft: theme.spacing(1),
			},
		},
		actionList: {
			top: "113px !important",
			[theme.breakpoints.down("md")]: {
				top: "100px !important",
			},
			"& .MuiMenuItem-root": {
				fontSize: "0.8rem",
			},
		},
		commands: {
			flex: "0 0 auto",
			marginTop: ({ useVerticalLayout }: { useVerticalLayout: boolean }) => (useVerticalLayout ? theme.spacing(0.25) : 0),
			marginLeft: ({ useVerticalLayout }: { useVerticalLayout: boolean }) => (useVerticalLayout ? 0 : theme.spacing(2)),
			[theme.breakpoints.down("md")]: {
				marginLeft: theme.spacing(1),
			},
			...centeredFlexRow,
		},
		command: {
			fontSize: "0.75rem",
			[theme.breakpoints.down("md")]: {
				padding: theme.spacing(0.5, 1),
				fontSize: "0.6rem",
			},
			"&:not(:last-child)": {
				marginRight: theme.spacing(1),
			},
		},
	})
);

interface StatusBarProps {
	game: GameStateDto;
	isMobile: boolean;
	playerId: Nullable<string>;
	isSpectator: boolean;
}

const StatusBar = ({ game, playerId, isSpectator, isMobile }: StatusBarProps) => {
	const { vm } = useGamePageContext();
	const statusMessage = selectStatusMessage(vm);
	const commands = selectAvailableCommands(vm);
	const availableActions = selectAvailableActions(vm);
	const isExecutingAction = vm.isExecutingAction;
	const isIdle = !isExecutingAction;
	const statusBarMessage = isExecutingAction ? "Executing..." : statusMessage;
	const [menuAnchor, setMenuAnchor] = useState<HTMLElement | null>(null);
	const { activeWorkflow, startWorkflow } = useWorkflow();
	const useVerticalLayout = isMobile && commands.length > 1;
	const classes = useStyles({ useVerticalLayout });
	const isActivePlayer = game.activePlayer?.id === playerId;
	const showActionSelector = isActivePlayer && !activeWorkflow;

	const handleCommand = (command: Command) => {
		if (!activeWorkflow) {
			throw new Error("How can you issue a command without an active workflow?!");
		}
		const action = activeWorkflow.handleCommand(command);
		if (!action) {
			return;
		}
		vm.executePlayerAction(game.id, action);
	};

	const onActionSelected = (action: AvailableActionDto) => {
		if (isSpectator) {
			return;
		}
		const workflow = fromAction(playerId!, game, action, vm);
		startWorkflow(workflow);
		setMenuAnchor(null);
	};

	return (
		<div className={classes.root}>
			<Typography variant="body1" component="div">
				<div className={classes.message + " gaia-font"}>{statusBarMessage}</div>
			</Typography>
			{!isSpectator && (
				<>
					{isIdle && (
						<div className={classes.commands}>
							{commands.map(cmd => (
								<Button
									key={`${cmd.nextState}§${cmd.text}`}
									className={classes.command}
									onClick={() => handleCommand(cmd)}
									variant="contained"
									color={cmd.isPrimary ? "primary" : undefined}
								>
									<span className="gaia-font">{cmd.text}</span>
								</Button>
							))}
						</div>
					)}
					{showActionSelector && (
						<div className={classes.actionSelector}>
							<Button className={classes.command} onClick={evt => setMenuAnchor(evt.currentTarget)} variant="contained" color="primary">
								<span className="gaia-font">Actions</span>
							</Button>
							<Menu
								anchorEl={menuAnchor}
								keepMounted
								open={!!menuAnchor}
								onClose={() => setMenuAnchor(null)}
								PaperProps={{
									className: classes.actionList,
								}}
							>
								{availableActions.map(action => (
									<MenuItem key={action.type} onClick={() => onActionSelected(action)}>
										<span className="gaia-font">{action.description}</span>
									</MenuItem>
								))}
							</Menu>
						</div>
					)}
				</>
			)}
		</div>
	);
};

export default observer(StatusBar);

// Frontend/ProjectSvelte/src/game-page/status-bar/StatusBar.svelte
<script lang="ts">
	import ListItem from "$components/list/ListItem.svelte";
	import ListItemText from "$components/list/ListItemText.svelte";
	import type { AvailableActionDto } from "$dto/interfaces";
	import { get } from "svelte/store";
	import { getGamePageContext } from "../GamePage.context";
	import type { Command } from "../workflows/types";
	import { fromAction } from "../workflows/utils";

	export let isMobile: boolean;

	const { store, activeWorkflow, startWorkflow } = getGamePageContext();
	const { availableActions, availableCommands, currentPlayer, game, isExecutingAction, isSpectator, statusMessage } = store;

	let showMenu = false;
	const openMenu = () => {
		showMenu = true;
	};
	const closeMenu = () => {
		showMenu = false;
	};

	const handleCommand = (command: Command) => {
		const wf = get(activeWorkflow);
		if (!wf) {
			throw new Error("How can you issue a command without an active workflow?!");
		}

		const action = wf.handleCommand(command);
		if (!action) {
			return;
		}

		store.executePlayerAction(get(game).id, action);
	};

	const selectAction = (action: AvailableActionDto) => {
		if ($isSpectator) {
			return;
		}

		const workflow = fromAction($currentPlayer!.id, $game, action, store);
		startWorkflow(workflow);
		closeMenu();
	};

	$: useVerticalLayout = isMobile && $availableCommands.length > 1;
	$: isActivePlayer = $game?.activePlayer?.id === $currentPlayer?.id;
	$: showActionSelector = isActivePlayer && !$activeWorkflow;
	$: statusBarMessage = $isExecutingAction ? "Executing..." : $statusMessage;
	$: {
		console.log({ statusBarMessage, isExecutingAction: $isExecutingAction });
	}
	$: isIdle = !$isExecutingAction;
</script>

<svelte:window on:click={closeMenu} />
<div
	class="flex items-center justify-center h-full gap-1 md:gap-3 py-1 px-2 md:py-2 md:px-4 bg-white shadow-sm shadow-gray-500"
	class:flex-col={useVerticalLayout}
>
	<div class="flex-initial text-xs md:text-sm text-center text-gray-900 gaia-font">{statusBarMessage}</div>
	{#if !$isSpectator}
		{#if isIdle}
			<div class="flex flex-shrink-0 gap-1 md:gap-3">
				{#each $availableCommands as cmd (`${cmd.nextState}§${cmd.text}`)}
					<ion-button
						size={isMobile ? "small" : "default"}
						color={cmd.isPrimary ? "primary" : undefined}
						on:click={() => handleCommand(cmd)}
					>
						<span class="gaia-font">{cmd.text}</span>
					</ion-button>
				{/each}
			</div>
		{/if}
		{#if showActionSelector}
			<div class="flex-shrink-0 ml-1 md:ml-3 relative">
				<ion-button size={isMobile ? "small" : "default"} color="primary" on:click={openMenu}>
					<span class="gaia-font">Actions</span>
				</ion-button>
				{#if showMenu}
					<div class="action-selector absolute top-0 right-0 p-2 border-2 rounded-lg border-gray-300 bg-white shadow-xl">
						{#each $availableActions as action (action.type)}
							<ListItem on:click={() => selectAction(action)}>
								<ListItemText text={action.description} size="sm" />
							</ListItem>
						{/each}
					</div>
				{/if}
			</div>
		{/if}
	{/if}
</div>

<style>
	.action-selector {
		min-width: 250px;
	}
</style>
