// Frontend/StarGate/src/game-page/game-board/player-area/PlayerTechnologyTile.tsx
import { createStyles, makeStyles } from "@material-ui/core/styles";
import _ from "lodash";
import { useSelector } from "react-redux";
import { TechnologyTileDto } from "../../../dto/interfaces";
import { interactiveElementClass } from "../../../utils/miscellanea";
import { selectOwnAdvancedTileInteractionState, selectOwnStandardTileInteractionState } from "../../store/active-game.slice";
import { useWorkflow } from "../../WorkflowContext";
import { InteractiveElementType } from "../../workflows/enums";
import ActionToken from "../ActionToken";
import AdvancedTechnologyTile from "../AdvancedTechnologyTile";
import StandardTechnologyTile from "../StandardTechnologyTile";

interface PlayerTechnologyTileProps {
	tile: TechnologyTileDto;
	playerId: string;
}

const useStyles = makeStyles(() =>
	createStyles({
		root: {
			width: "100%",
			position: "relative",
		},
		advancedTile: {
			position: "absolute",
			width: "82.5%",
			top: "8%",
			left: "5%",
		},
		actionToken: {
			position: "absolute",
			width: "50%",
			top: "17%",
			left: "25%",
			"&.advanced": {
				top: "12%",
				left: "16%",
			},
		},
	})
);

const PlayerTechnologyTile = ({ tile, playerId }: PlayerTechnologyTileProps) => {
	const classes = useStyles();
	const covered = !_.isNil(tile.coveredByAdvancedTile);
	const tileId = covered ? tile.coveredByAdvancedTile! : tile.id;
	const selector = covered ? selectOwnAdvancedTileInteractionState(tile.coveredByAdvancedTile!) : selectOwnStandardTileInteractionState(tile.id);
	const { isClickable, isSelected } = useSelector(_.partialRight(selector, playerId));
	const { activeWorkflow } = useWorkflow();
	const tileClicked = isClickable
		? () => {
				activeWorkflow?.elementSelected(tileId, covered ? InteractiveElementType.OwnAdvancedTile : InteractiveElementType.OwnStandardTile);
		  }
		: _.noop;

	return (
		<div className={classes.root}>
			<StandardTechnologyTile type={tile.id} />
			{covered && (
				<div className={classes.advancedTile}>
					<AdvancedTechnologyTile type={tile.coveredByAdvancedTile!} />
				</div>
			)}
			<div className={classes.actionToken + (covered ? " advanced" : "")}>{tile.used && <ActionToken />}</div>
			<div className={interactiveElementClass(isClickable, isSelected)} onClick={tileClicked}></div>
		</div>
	);
};

export default PlayerTechnologyTile;

// Frontend/ProjectSvelte/src/game-page/game-board/players/PlayerTechnologyTile.svelte
<script lang="ts">
	import type { TechnologyTileDto } from "$dto/interfaces";
	import { interactiveElementClass } from "$utils/miscellanea";
	import { InteractiveElementType } from "$utils/types";
	import { isNil, noop } from "lodash";
	import { get } from "svelte/store";
	import { getGamePageContext } from "../../GamePage.context";
	import { deriveOwnAdvancedTileInteractionState, deriveOwnStandardTileInteractionState } from "../../store/selectors";
	import ActionToken from "../ActionToken.svelte";
	import AdvancedTechnologyTile from "../AdvancedTechnologyTile.svelte";
	import StandardTechnologyTile from "../StandardTechnologyTile.svelte";

	export let tile: TechnologyTileDto;
	export let playerId: string;

	const { store, activeWorkflow } = getGamePageContext();

	let clickable = false;
	let selected = false;
	let tileClicked = noop;
	$: {
		const covered = !isNil(tile.coveredByAdvancedTile);
		const tileId = covered ? tile.coveredByAdvancedTile! : tile.id;
		const selector = covered
			? deriveOwnAdvancedTileInteractionState(tile.coveredByAdvancedTile!)
			: deriveOwnStandardTileInteractionState(tile.id);
		const interactionState = selector(store, playerId);
		const state = get(interactionState);
		clickable = state.clickable;
		selected = state.selected;
		tileClicked = clickable
			? () => {
					$activeWorkflow?.elementSelected(
						tileId,
						covered ? InteractiveElementType.OwnAdvancedTile : InteractiveElementType.OwnStandardTile
					);
			  }
			: noop;
	}
</script>

<div class="player-technology-tile w-full relative" class:interactive={clickable || selected}>
	<StandardTechnologyTile type={tile.id} />
	{#if tile.coveredByAdvancedTile}
		<div class="advanced-tile absolute">
			<AdvancedTechnologyTile type={tile.coveredByAdvancedTile} />
			<div class="action-token advanced">
				{#if tile.used}
					<ActionToken />
				{/if}
			</div>
		</div>
	{:else}
		<div class="action-token advanced">
			{#if tile.used}
				<ActionToken />
			{/if}
		</div>
	{/if}
	<div class={interactiveElementClass(clickable, selected)} style:pointer-events="all" on:click|stopPropagation={tileClicked} />
</div>

<style>
	.player-technology-tile:not(.interactive):hover .advanced-tile {
		transform: rotateX(90deg);
		transition: transform 250ms;
	}

	.advanced-tile {
		width: 82.5%;
		top: 8%;
		left: 5%;
	}

	.action-token {
		position: absolute;
		width: 50%;
		top: 20%;
		left: 25%;
	}

	.action-token.advanced {
		width: 64%;
		top: 5%;
		left: 10%;
	}
</style>
