// Frontend/Portal/src/game-page/game-board/player-area/PlayerArea.tsx
import _ from "lodash";
import { PlayerInGameDto } from "../../../dto/interfaces";
import FederationToken from "../federation-token/FederationToken";
import PlayerBoard from "../player-board/PlayerBoard";
import RoundBooster from "../round-booster/RoundBooster";
import useStyles from "./player-area.styles";
import PlayerTechnologyTile from "./PlayerTechnologyTile";

interface PlayerAreaProps {
	player: PlayerInGameDto;
	framed: boolean;
}

const PlayerArea = ({ player, framed }: PlayerAreaProps) => {
	const classes = useStyles();

	if (_.isNil(player.state)) {
		return <div></div>;
	}

	return (
		<div className={classes.root + (framed ? " with-frame" : "")}>
			<div className={classes.upper}>
				<div className={classes.board}>
					<PlayerBoard player={player} />
				</div>
				<div className="spacer"></div>
				<div className={classes.boosterAndFederations}>
					{!!player.state.roundBooster && (
						<div className={classes.booster}>
							<RoundBooster booster={player.state.roundBooster} withPlayerInfo={true} />
						</div>
					)}
					<div className={classes.federations}>
						{_.map(player.state.federationTokens, (token, index) => (
							<div key={index} className={classes.federation}>
								<FederationToken type={token.id} playerId={player.id} used={token.usedForTechOrAdvancedTile} />
							</div>
						))}
					</div>
				</div>
			</div>
			{!_.isEmpty(player.state.technologyTiles) && (
				<div className={classes.techTiles}>
					{_.map(player.state.technologyTiles, tile => (
						<div key={tile.id} className={classes.techTile}>
							<PlayerTechnologyTile tile={tile} playerId={player.id} />
						</div>
					))}
				</div>
			)}
		</div>
	);
};

export default PlayerArea;

// Frontend/ProjectSvelte/src/game-page/game-board/players/PlayerArea.svelte
<script lang="ts" context="module">
	const BOOSTER_TO_BOARD_RATIO = 16;
</script>

<script lang="ts">
	import type { PlayerInGameDto } from "$dto/interfaces";
	import { isEmpty, isNil } from "lodash";
	import FederationToken from "../FederationToken.svelte";
	import RoundBooster from "../RoundBooster.svelte";
	import PlayerTechnologyTile from "./PlayerTechnologyTile.svelte";

	export let player: PlayerInGameDto;
	export let framed = true;
</script>

{#if !isNil(player.state)}
	<div class={framed ? "p-1 sm:p-2 md:p-2 border-1 md:border-2 border-gray-500 rounded-md" : ""}>
		<div class="flex items-stretch">
			<div class="flex-initial" style:width={`calc(100% * ${BOOSTER_TO_BOARD_RATIO - 1} / ${BOOSTER_TO_BOARD_RATIO})`}>
				<!-- <PlayerBoard player={player} /> -->
			</div>
			<div class="flex-shrink-0 w-2 sm:w-3 md:w-4" />
			<div class="flex flex-col flex-shrink-0" style:width={`calc(100% / ${BOOSTER_TO_BOARD_RATIO})`}>
				{#if player.state.roundBooster}
					<div class="w-full mb-2 md:mb-4">
						<RoundBooster booster={player.state.roundBooster} withPlayerInfo={true} />
					</div>
				{/if}
				<div class="w-full flex flex-wrap justify-center">
					{#each player.state.federationTokens as token, index (index)}
						<div class="w-3/4 mb-3 last:mb-0">
							<FederationToken type={token.id} playerId={player.id} used={token.usedForTechOrAdvancedTile} />
						</div>
					{/each}
				</div>
			</div>
		</div>
		{#if !isEmpty(player.state.technologyTiles)}
			<div class="flex flex-wrap mt-1 md:mt-3">
				{#each player.state.technologyTiles as tile (tile.id)}
					<div class="tech-tile mr-1 md:mr-3">
						<PlayerTechnologyTile {tile} playerId={player.id} />
					</div>
				{/each}
			</div>
		{/if}
	</div>
{/if}

<style>
	.tech-tile {
		width: 10%;
	}
</style>
