// Frontend/ProjectSvelte/src/game-page/game-board/scoring-board/ScoringBoard.svelte
<script lang="ts">
	import type { FederationTokenStackDto, RoundBoosterTileDto, ScoringTrackDto } from "$dto/interfaces";
	import RoundBooster from "../RoundBooster.svelte";
	import FederationTokenStack from "./FederationTokenStack.svelte";
	import ScoringTrack from "./scoring-track/ScoringTrack.svelte";

	export let board: ScoringTrackDto;
	export let roundBoosters: RoundBoosterTileDto[];
	export let federationTokens: FederationTokenStackDto[];
	export let isMobile = false;
</script>

<div class="scoring-board fill-parent">
	<div class="container">
		<div class="grid">
			<div class="grid">
				<ScoringTrack {board} />
			</div>
			<div class="grid">
				<div class="round-boosters fill-parent">
					{#each roundBoosters as booster (booster.id)}
						<div class="booster">
							<RoundBooster {booster} />
						</div>
					{/each}
				</div>
			</div>
			<div class="grid">
				<div class="federation-tokens fill-parent">
					{#each federationTokens.filter(stack => stack.remaining > 0) as stack (stack.type)}
						<div class="stack">
							<FederationTokenStack {stack} />
						</div>
					{/each}
				</div>
			</div>
		</div>
	</div>
</div>

<style>
	.scoring-board {
		align-self: flex-start;
		overflow: hidden;
	}

	.round-boosters {
		display: flex;
		flex-wrap: wrap;
		align-items: flex-start;
	}

	.round-boosters > .booster {
		width: calc((100% - 4 * (8px)) / 5);
		max-width: 100px;
		margin: 0 8px 8px 0;
	}

	.round-boosters > .booster:last-child {
		margin-right: 0;
	}

	.federation-tokens {
		display: flex;
		flex-wrap: wrap;
		align-items: flex-start;
	}

	.federation-tokens > .stack {
		width: 6%;
		min-width: 75px;
		max-width: 150px;
		margin: 0 12px 12px 0;
	}
</style>

// Frontend/Portal/src/game-page/game-board/scoring-board/ScoringBoard.tsx
import Container from "@mui/material/Container";
import Grid from "@mui/material/Grid";
import _ from "lodash";
import { FederationTokenStackDto, RoundBoosterTileDto, ScoringTrackDto } from "../../../dto/interfaces";
import FederationTokenStack from "../federation-token/FederationTokenStack";
import RoundBooster from "../round-booster/RoundBooster";
import ScoringTrack from "../scoring-track/ScoringTrack";
import useStyles from "./scoring-board.styles";

interface ScoringBoardProps {
	board: ScoringTrackDto;
	roundBoosters: RoundBoosterTileDto[];
	federationTokens: FederationTokenStackDto[];
	isMobile: boolean;
}

const ScoringBoard = ({ board, roundBoosters, federationTokens, isMobile }: ScoringBoardProps) => {
	const classes = useStyles({ isMobile });

	return (
		<div className={classes.root}>
			<Container maxWidth="lg" disableGutters={isMobile}>
				<Grid container spacing={isMobile ? 0 : 2}>
					<Grid item xs={12} md={6}>
						<ScoringTrack board={board} />
					</Grid>
					<Grid item xs={12} md={6}>
						<div className={classes.roundBoosters}>
							{_.map(roundBoosters, booster => (
								<div key={booster.id} className="booster">
									<RoundBooster booster={booster} withPlayerInfo={false} />
								</div>
							))}
						</div>
					</Grid>
					<Grid item xs={12}>
						<div className={classes.federationTokens}>
							{_.chain(federationTokens)
								.filter(stack => stack.remaining > 0)
								.map(stack => (
									<div key={stack.type} className="stack">
										<FederationTokenStack stack={stack} />
									</div>
								))
								.value()}
						</div>
					</Grid>
				</Grid>
			</Container>
		</div>
	);
};

export default ScoringBoard;
