// Frontend/Portal/src/game-page/game-board/hex/LostPlanet.tsx
import createStyles from '@mui/styles/createStyles';
import makeStyles from '@mui/styles/makeStyles';
import LostPlanetImg from "../../../assets/Resources/Markers/LostPlanet.png";
import { Race } from "../../../dto/enums";
import Satellite from "./Satellite";

interface LostPlanetProps {
	width: number;
	height: number;
	raceId: Race;
}

const useStyles = makeStyles(() =>
	createStyles({
		root: {
			position: "relative",
			width: "100%",
			height: "100%",
		},
		lostPlanet: {
			position: "absolute",
			width: ({ width }: LostPlanetProps) => width * 0.75,
			height: ({ width }: LostPlanetProps) => width * 0.75,
			top: ({ height }: LostPlanetProps) => (height * 0.25) / 2,
			left: ({ width }: LostPlanetProps) => (width * 0.25) / 2,
		},
		satellite: {
			position: "absolute",
			top: ({ height }: LostPlanetProps) => height * 0.65,
			left: ({ width }: LostPlanetProps) => width * 0.2,
		},
	})
);

const LostPlanet = (props: LostPlanetProps) => {
	const classes = useStyles(props);

	return (
		<div className={classes.root}>
			<img className={classes.lostPlanet} src={LostPlanetImg} alt="" />
			<div className={classes.satellite}>
				<Satellite raceId={props.raceId} width={props.height / 4} />
			</div>
		</div>
	);
};

export default LostPlanet;

// Frontend/ProjectSvelte/src/game-page/game-board/hex/LostPlanet.svelte
<script lang="ts">
	import type { Race } from "../../../dto/enums";
	import { assetUrl } from "../../../utils/miscellanea";
	import Satellite from "./Satellite.svelte";

	export let raceId: Race;
	export let width: number;
</script>

<div class="root">
	<img class="lost-planet" src={assetUrl("Markers/LostPlanet.png")} alt="" />
	<div class="satellite-wrapper">
		<Satellite {raceId} width={width / 5} />
	</div>
</div>

<style>
	.root {
		position: relative;
		width: 100%;
		height: 100%;
	}

	.lost-planet {
		position: absolute;
		width: 75%;
		left: 12.5%;
		top: 7.5%;
	}

	.satellite-wrapper {
		position: absolute;
		right: 20%;
		bottom: 20%;
	}
</style>
