// Frontend/Portal/src/game-page/game-board/sector/Sector.tsx
import Sector1 from "../../../assets/Resources/Sectors/1.png";
import Sector10 from "../../../assets/Resources/Sectors/10.png";
import Sector2 from "../../../assets/Resources/Sectors/2.png";
import Sector3 from "../../../assets/Resources/Sectors/3.png";
import Sector4 from "../../../assets/Resources/Sectors/4.png";
import Sector5 from "../../../assets/Resources/Sectors/5.png";
import Sector5Outlined from "../../../assets/Resources/Sectors/5outlined.png";
import Sector6 from "../../../assets/Resources/Sectors/6.png";
import Sector6Outlined from "../../../assets/Resources/Sectors/6outlined.png";
import Sector7 from "../../../assets/Resources/Sectors/7.png";
import Sector7Outlined from "../../../assets/Resources/Sectors/7outlined.png";
import Sector8 from "../../../assets/Resources/Sectors/8.png";
import Sector9 from "../../../assets/Resources/Sectors/9.png";
import { SectorDto } from "../../../dto/interfaces";
import Hex from "../hex/Hex";
import useStyles from "./sector.styles";

const sectorBackgrounds = new Map<string, string>([
	["1", Sector1],
	["2", Sector2],
	["3", Sector3],
	["4", Sector4],
	["5", Sector5],
	["5outlined", Sector5Outlined],
	["6", Sector6],
	["6outlined", Sector6Outlined],
	["7", Sector7],
	["7outlined", Sector7Outlined],
	["8", Sector8],
	["9", Sector9],
	["10", Sector10],
]);

interface SectorProps {
	sector: SectorDto;
	hexWidth: number;
	hexHeight: number;
	xOffset: number;
	yOffset: number;
}

const Sector = ({ sector, hexWidth, hexHeight, xOffset, yOffset }: SectorProps) => {
	const classes = useStyles({
		hexWidth,
		hexHeight,
		row: sector.row,
		column: sector.column,
		xOffset,
		yOffset,
		rotation: sector.rotation,
	});

	return (
		<div className={classes.sector}>
			<img className={classes.image} src={sectorBackgrounds.get(sector.id)} alt="" />
			{sector.hexes.map(hex => (
				<Hex key={hex.id} hex={hex} width={hexWidth} />
			))}
		</div>
	);
};

export default Sector;

// Frontend/ProjectSvelte/src/game-page/game-board/map/Sector.svelte
<script lang="ts" context="module">
	import { hexSpike, tileHeight, tileWidth } from "./shape-utils";

	const getX = (column: number, hexWidth: number) => {
		const columnWidth = hexWidth - hexSpike(hexWidth);
		return columnWidth * column;
	};

	const getY = (row: number, hexHeight: number) => {
		const rowHeight = hexHeight / 2;
		return rowHeight * row;
	};

	const getSectorWidth = (hexWidth: number) => {
		return tileWidth(hexWidth);
	};

	const getSectorHeight = (hexWidth: number, hexHeight: number) => {
		return tileHeight(hexWidth, hexHeight);
	};
</script>

<script lang="ts">
	import type { SectorDto } from "$dto/interfaces";
	import { assetUrl } from "$utils/miscellanea";
	import Hex from "./hex/Hex.svelte";

	export let sector: SectorDto;
	export let hexWidth: number;
	export let hexHeight: number;
	export let xOffset: number;
	export let yOffset: number;

	$: style = `
	width: ${getSectorWidth(hexWidth)}px;
	height: ${getSectorHeight(hexWidth, hexHeight)}px;
	top: ${getY(sector.row, hexHeight) + yOffset}px;
	left: ${getX(sector.column, hexWidth) + xOffset}px;
	`;
	$: imgRotation = `rotateZ(-${sector.rotation * 60}deg)`;
</script>

<div class="sector" {style}>
	<img class="image" style:transform={imgRotation} src={assetUrl(`Sectors/${sector.id}.png`)} alt="" />
	{#each sector.hexes as hex (hex.id)}
		<Hex {hex} width={hexWidth} />
	{/each}
</div>

<style>
	.sector {
		position: absolute;
		overflow: hidden;
		pointer-events: none;
	}

	.image {
		position: absolute;
		width: 100%;
		height: 100%;
		top: 0;
		left: 0;
	}
</style>
