// Frontend/StarGate/src/game-page/main-view/turn-order/TurnOrderMinimap.tsx
import { useTheme } from "@material-ui/core/styles";
import Typography from "@material-ui/core/Typography";
import _ from "lodash";
import { useSelector } from "react-redux";
import { GamePhase, Race } from "../../../dto/enums";
import { GameStateDto } from "../../../dto/interfaces";
import { useAssetUrl } from "../../../utils/hooks";
import { isAuctionOngoing, isLastRound, Nullable } from "../../../utils/miscellanea";
import { getRaceImage } from "../../../utils/race-utils";
import { selectSortedActivePlayers, selectSortedPassedPlayers } from "../../store/active-game.slice";
import { RACE_AVATAR_WIDTH } from "../main-view.styles";
import useStyles from "./turn-order-minimap.styles";

const OngoingAuction = ({ race, username, orderLabel }: { race: Race; username: string; orderLabel: string }) => {
	const theme = useTheme();
	const imgUrl = useAssetUrl(`Races/${getRaceImage(race)}`);
	return (
		<div style={{ display: "flex", alignItems: "center", justifyContent: "flex-start" }}>
			<div style={{ position: "relative" }}>
				<div className="gaia-font" style={{ position: "absolute", bottom: 0, left: 0, color: "white" }}>
					{orderLabel}
				</div>
				<img style={{ width: RACE_AVATAR_WIDTH }} src={imgUrl} alt="" />
			</div>
			<Typography
				variant="caption"
				className="gaia-font"
				style={{ marginLeft: theme.spacing(1), maxWidth: 100, overflowX: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}
			>
				{username}
			</Typography>
		</div>
	);
};

const PlayerAvatar = ({ race, username, orderLabel }: { race: Nullable<Race>; username: string; orderLabel: string }) => {
	const imgUrl = useAssetUrl(`Races/${getRaceImage(race)}`);
	return race ? (
		<div style={{ position: "relative" }}>
			<div className="gaia-font" style={{ position: "absolute", bottom: 0, left: 0, color: "white" }}>
				{orderLabel}
			</div>
			<img style={{ width: RACE_AVATAR_WIDTH }} src={imgUrl} alt="" />
		</div>
	) : (
		<Typography variant="body1" className="gaia-font">
			{username}
		</Typography>
	);
};

interface TurnOrderMinimapProps {
	game: GameStateDto;
}

const TurnOrderMinimap = ({ game }: TurnOrderMinimapProps) => {
	const classes = useStyles();
	const isAuctioning = isAuctionOngoing(game);
	const isLastRound_ = isLastRound(game);
	const activePlayers = useSelector(selectSortedActivePlayers);
	const passedPlayers = useSelector(selectSortedPassedPlayers);

	if (isAuctioning) {
		return (
			<div className={classes.root}>
				<div className={classes.roundColumn}>
					<div className="gaia-font">Auction</div>
					{_.map(game.auctionState!.auctionedRaces, (auction, index) => (
						<div key={index} className={classes.ongoingAuction}>
							<OngoingAuction race={auction.race} username={auction.playerUsername ?? "No bid"} orderLabel={`${auction.order + 1}°`} />
						</div>
					))}
				</div>
			</div>
		);
	}

	return (
		<div className={classes.root}>
			<div className={classes.roundColumn}>
				<div className="gaia-font">Round {game.currentRound}</div>
				{_.map(activePlayers, p => (
					<div key={p.id} className={classes.avatar}>
						<PlayerAvatar race={p.raceId} username={p.username} orderLabel={`${p.state?.currentRoundTurnOrder ?? 0}°`} />
					</div>
				))}
			</div>
			{game.currentPhase !== GamePhase.Setup && !isLastRound_ && _.some(passedPlayers) && (
				<div className={`${classes.roundColumn} ${classes.nextRound}`}>
					<div className="gaia-font">Round {game.currentRound + 1}</div>
					{_.map(passedPlayers, pp => (
						<div key={pp.id} className={classes.avatar}>
							<PlayerAvatar race={pp.raceId} username={pp.username} orderLabel={`${pp.state!.nextRoundTurnOrder}°`} />
						</div>
					))}
				</div>
			)}
		</div>
	);
};

export default TurnOrderMinimap;

// Frontend/ProjectSvelte/src/game-page/turn-order/TurnOrderMinimap.svelte
<script lang="ts">
	import { GamePhase } from "$dto/enums";
	import type { GameStateDto } from "$dto/interfaces";
	import { isAuctionOngoing, isLastRound } from "$utils/miscellanea";
	import { selectSortedActivePlayers, selectSortedPassedPlayers } from "$utils/selectors";
	import { some } from "lodash";
	import OngoingAuction from "./OngoingAuction.svelte";
	import PlayerAvatar from "./PlayerAvatar.svelte";

	export let game: GameStateDto;
	export let direction: "vertical" | "horizontal";

	const isAuctioning = isAuctionOngoing(game);
	const auctionedRaces = game.auctionState?.auctionedRaces ?? [];
	const isLastRound_ = isLastRound(game);
	const activePlayers = selectSortedActivePlayers(game);
	const passedPlayers = selectSortedPassedPlayers(game);
</script>

{#if isAuctioning}
	<div class="p-2 bg-gray-900 border-2 border-gray-400 border-solid rounded-lg">
		<div class="gaia-font">Auction</div>
		<div class={direction === "vertical" ? "flex flex-col justify-center items-center" : "flex"}>
			{#each auctionedRaces as auction, index (index)}
				<div class="w-full">
					<OngoingAuction
						race={auction.race}
						username={auction.playerUsername ?? "No bid"}
						orderLabel={`${auction.order + 1}°`}
					/>
				</div>
			{/each}
		</div>
	</div>
{:else}
	<div class="p-2 bg-gray-900 border-2 border-gray-400 border-solid rounded-lg">
		<div>
			<p class="m-0 text-white gaia-font">
				Round {game.currentRound}
			</p>
			<div class={direction === "vertical" ? "flex flex-col justify-center items-center" : "flex"}>
				{#each activePlayers as p (p.id)}
					<div class={direction === "vertical" ? "mt-1" : "ml-2"}>
						<PlayerAvatar race={p.raceId} username={p.username} orderLabel={`${p.state?.currentRoundTurnOrder ?? 0}°`} />
					</div>
				{/each}
			</div>
		</div>
		{#if game.currentPhase !== GamePhase.Setup && !isLastRound_ && some(passedPlayers)}
			<div class="ml-2">
				<p class="m-0 text-white gaia-font">
					Round {game.currentRound + 1}
				</p>
				<div class={direction === "vertical" ? "flex flex-col justify-center items-center" : "flex"}>
					{#each passedPlayers as pp (pp.id)}
						<div class={direction === "vertical" ? "mt-1" : "ml-2"}>
							<PlayerAvatar race={pp.raceId} username={pp.username} orderLabel={`${pp.state.nextRoundTurnOrder}°`} />
						</div>
					{/each}
				</div>
			</div>
		{/if}
	</div>
{/if}
