// Frontend/StarGate/src/game-page/game-board/research-track/PlayerAdvancement.tsx
import { createStyles, makeStyles } from "@material-ui/core/styles";
import { Race } from "../../../dto/enums";
import PlayerMarker from "../PlayerMarker";

const percentY = new Map<number, number>([
	[0, 87],
	[1, 75],
	[2, 63],
	[3, 44],
	[4, 32],
	[5, 5],
]);

interface PlayerAdvancementProps {
	raceId: Race;
	steps: number;
	width: number;
}

const useStyles = makeStyles(() =>
	createStyles({
		root: {
			position: "relative",
			width: "100%",
			height: "100%",
		},
		marker: {
			position: "absolute",
			width: ({ width }: PlayerAdvancementProps) => width * 0.6,
			top: ({ steps }: PlayerAdvancementProps) => `${percentY.get(steps)!}%`,
			left: ({ width }: PlayerAdvancementProps) => `calc(50% - ${(width * 0.6) / 2}px)`,
		},
	})
);

const PlayerAdvancement = (props: PlayerAdvancementProps) => {
	const classes = useStyles(props);
	return (
		<div className={classes.root}>
			<div className={classes.marker}>
				<PlayerMarker race={props.raceId} />
			</div>
		</div>
	);
};

export default PlayerAdvancement;

// Frontend/ProjectSvelte/src/game-page/game-board/research-board/research-track/PlayerAdvancement.svelte
<script lang="ts" context="module">
	const percentY = new Map<number, number>([
		[0, 87],
		[1, 75],
		[2, 63],
		[3, 44],
		[4, 32],
		[5, 5],
	]);
</script>

<script lang="ts">
	import type { Race } from "$dto/enums";
	import PlayerMarker from "../../PlayerMarker.svelte";

	export let race: Race;
	export let width: number;
	export let steps: number;

	$: style = `width: ${width * 0.6}px; top: ${percentY.get(steps) ?? 0}%; left: calc(50% - ${(width * 0.6) / 2}px)`;
</script>

<div class="player-advancement">
	<div class="marker-wrapper" {style}>
		<PlayerMarker {race} />
	</div>
</div>

<style>
	.player-advancement {
		position: relative;
		width: 100%;
		height: 100%;
	}

	.marker-wrapper {
		position: absolute;
	}
</style>
