// Frontend/Portal/src/game-page/game-board/research-track/ResearchTrack.tsx
import { noop, isNil } from "lodash";
import { observer } from "mobx-react";
import LostPlanetToken from "../../../assets/Resources/Markers/LostPlanet.png";
import { ResearchTrackDto } from "../../../dto/interfaces";
import { ElementSize } from "../../../utils/hooks";
import { interactiveElementClass } from "../../../utils/miscellanea";
import { useGamePageContext } from "../../GamePage.context";
import { selectResearchTrackInteractionState } from "../../store/selectors";
import { useWorkflow } from "../../WorkflowContext";
import { InteractiveElementType } from "../../workflows/enums";
import AdvancedTechnologyTile from "../AdvancedTechnologyTile";
import FederationToken from "../federation-token/FederationToken";
import TechnologyTileStack from "../TechnologyTileStack";
import PlayerAdvancement from "./PlayerAdvancement";
import useStyles from "./research-track.styles";

interface ResearchTrackProps extends ElementSize {
	track: ResearchTrackDto;
}

const ResearchTrack = ({ track, width, height }: ResearchTrackProps) => {
	const classes = useStyles({ width, height });
	const { vm } = useGamePageContext();
	const { isClickable, isSelected } = selectResearchTrackInteractionState(track.id)(vm);
	const { activeWorkflow } = useWorkflow();
	const trackClicked = isClickable
		? () => {
				activeWorkflow?.elementSelected(track.id, InteractiveElementType.ResearchStep);
		  }
		: noop;
	const playerAdvancementWidth = width * 0.25;

	return (
		<div className={classes.researchTrack + " research-track"}>
			{!isNil(track.federation) && (
				<div className={classes.federationToken}>
					<FederationToken type={track.federation} />
				</div>
			)}
			{track.lostPlanet && <img className={classes.lostPlanetToken} src={LostPlanetToken} alt="" />}
			{!isNil(track.advancedTileType) && (
				<div className={classes.advancedTile}>
					<AdvancedTechnologyTile type={track.advancedTileType} />
				</div>
			)}
			<div className={classes.playerMarkers}>
				{track.players.map(playerAdvancement => (
					<PlayerAdvancement key={playerAdvancement.raceId} width={playerAdvancementWidth} raceId={playerAdvancement.raceId} steps={playerAdvancement.steps} />
				))}
			</div>
			<div className={classes.standardTiles}>
				<TechnologyTileStack stack={track.standardTiles} />
			</div>
			<div className={interactiveElementClass(isClickable, isSelected)} onClick={trackClicked}></div>
		</div>
	);
};

export default observer(ResearchTrack);

// Frontend/ProjectSvelte/src/game-page/game-board/research-board/research-track/ResearchTrack.svelte
<script lang="ts">
	import type { ResearchTrackDto } from "$dto/interfaces";
	import { assetUrl, interactiveElementClass } from "$utils/miscellanea";
	import { InteractiveElementType } from "$utils/types";
	import { isNil, noop } from "lodash";
	import { getGamePageContext } from "../../../GamePage.context";
	import { deriveResearchTrackInteractionState } from "../../../store/selectors";
	import AdvancedTechnologyTile from "../../AdvancedTechnologyTile.svelte";
	import FederationToken from "../../FederationToken.svelte";
	import TechnologyTileStack from "../TechnologyTileStack.svelte";
	import PlayerAdvancement from "./PlayerAdvancement.svelte";

	export let track: ResearchTrackDto;
	export let width: number;
	export let height: number;

	const { store, activeWorkflow } = getGamePageContext();
	const interactionState = deriveResearchTrackInteractionState(track.id)(store);
	$: ({ clickable, selected } = $interactionState);
	$: trackClicked = clickable
		? () => {
				$activeWorkflow?.elementSelected(track.id, InteractiveElementType.ResearchStep);
		  }
		: noop;
	$: style = `width: ${width}px; height: ${height}px`;
</script>

<div class="research-track" {style}>
	{#if !isNil(track.federation)}
		<div class="federation-token">
			<FederationToken type={track.federation} />
		</div>
	{/if}
	{#if track.lostPlanet}
		<img class="lostPlanetToken" src={assetUrl("Markers/LostPlanet.png")} alt="" />
	{/if}
	{#if track.advancedTileType}
		<div class="advanced-tile">
			<AdvancedTechnologyTile type={track.advancedTileType} />
		</div>
	{/if}
	<div class="player-markers">
		{#each track.players as playerAdvancement}
			<PlayerAdvancement width={width * 0.25} race={playerAdvancement.raceId} steps={playerAdvancement.steps} />
		{/each}
	</div>
	<div class="standard-tiles">
		<TechnologyTileStack stack={track.standardTiles} />
	</div>
	<div class={interactiveElementClass(clickable, selected)} on:click={trackClicked} />
</div>

<style>
	.research-track {
		position: relative;
		display: flex;
		flex-direction: column;
	}

	.federation-token {
		width: 32%;
		position: absolute;
		top: 1%;
		left: 38%;
	}

	.lostPlanetToken {
		position: absolute;
		top: 1%;
		left: 30%;
		height: 9%;
	}

	.advanced-tile {
		width: 78%;
		position: absolute;
		top: 10.5%;
		left: 19%;
	}

	.player-markers {
		display: flex;
		width: 100%;
		flex: 1 1 100%;
	}

	.standard-tiles {
		flex: 1 0 auto;
		align-self: center;
		width: 95%;
	}
</style>
