// Frontend/Portal/src/game-page/game-board/scoring-track/FinalScoringTrack.tsx
import createStyles from "@mui/styles/createStyles";
import makeStyles from "@mui/styles/makeStyles";
import { useRef } from "react";
import { FinalScoringTileType } from "../../../dto/enums";
import { FinalScoringStateDto } from "../../../dto/interfaces";
import { ElementSize, useAssetUrl, useContainerDimensions } from "../../../utils/hooks";
import { fillParent } from "../../../utils/miscellanea";
import PlayerFinalScoringAdvancement from "./PlayerFinalScoringAdvancement";

const WIDTH_TO_HEIGHT_RATIO = 4.85;
const TILE_WIDTH_TO_HEIGHT_RATIO = 1.6;

const finalScoringTileNames = new Map<FinalScoringTileType, string>([
	[FinalScoringTileType.BuildingsInAFederation, "FINfed"],
	[FinalScoringTileType.BuildingsOnTheMap, "FINbld"],
	[FinalScoringTileType.KnownPlanetTypes, "FINtyp"],
	[FinalScoringTileType.GaiaPlanets, "FINgai"],
	[FinalScoringTileType.Sectors, "FINsec"],
	[FinalScoringTileType.Satellites, "FINsat"],
]);

interface FinalScoringTrackProps {
	scoring: FinalScoringStateDto;
}

const useStyles = makeStyles(() =>
	createStyles({
		finalScoringTrack: {
			display: "block",
			width: "100%",
			height: ({ height }: ElementSize) => height,
		},
		wrapper: {
			display: "flex",
			...fillParent,
		},
		playerScorings: {
			height: ({ height }: ElementSize) => height,
			flex: "1 1 auto",
			"& > .player-scoring": {
				height: "25%",
			},
		},
		tile: {
			width: ({ height }: ElementSize) => height * TILE_WIDTH_TO_HEIGHT_RATIO,
			height: "100%",
			flex: "0 0 auto",
			marginLeft: "auto",
			"& > img": {
				...fillParent,
			},
		},
	})
);

const FinalScoringTrack = ({ scoring }: FinalScoringTrackProps) => {
	const ref = useRef<HTMLDivElement>(null);
	const { width } = useContainerDimensions(ref);
	const height = width / WIDTH_TO_HEIGHT_RATIO;
	const scoringTileImg = useAssetUrl(`Boards/FinalScoring/${finalScoringTileNames.get(scoring.tileId)}.png`);
	const classes = useStyles({ width, height });

	return (
		<div ref={ref} className={classes.finalScoringTrack}>
			<div className={classes.wrapper}>
				<div className={classes.playerScorings}>
					{scoring.players.map(playerAdvancement => (
						<div key={playerAdvancement.player.id} className="player-scoring">
							<PlayerFinalScoringAdvancement playerStatus={playerAdvancement} />
						</div>
					))}
				</div>
				<div className={classes.tile}>
					<img src={scoringTileImg} alt="" />
				</div>
			</div>
		</div>
	);
};

export default FinalScoringTrack;

// Frontend/ProjectSvelte/src/game-page/game-board/scoring-board/scoring-track/FinalScoringTrack.svelte
<script lang="ts" context="module">
	import { FinalScoringTileType } from "$dto/enums";

	const WIDTH_TO_HEIGHT_RATIO = 4.85;
	const TILE_WIDTH_TO_HEIGHT_RATIO = 1.6;

	const finalScoringTileNames = new Map<FinalScoringTileType, string>([
		[FinalScoringTileType.BuildingsInAFederation, "FINfed"],
		[FinalScoringTileType.BuildingsOnTheMap, "FINbld"],
		[FinalScoringTileType.KnownPlanetTypes, "FINtyp"],
		[FinalScoringTileType.GaiaPlanets, "FINgai"],
		[FinalScoringTileType.Sectors, "FINsec"],
		[FinalScoringTileType.Satellites, "FINsat"],
	]);
</script>

<script lang="ts">
	import type { FinalScoringStateDto } from "$dto/interfaces";
	import { assetUrl } from "$utils/miscellanea";
	import { onMount } from "svelte";

	export let scoring: FinalScoringStateDto;

	let container: HTMLDivElement;
	let width = 0;

	onMount(() => {
		width = container.clientWidth;
	});

	$: height = width / WIDTH_TO_HEIGHT_RATIO;
</script>

<div class="final-scoring-track" style:height={`${height}px`} bind:this={container}>
	<div class="wrapper fill-parent">
		<div class="player-scorings" style:height={`${height}px`}>
			{#each scoring.players as playerAdvancement (playerAdvancement.player.id)}
				<div class="player-scoring">
					<!-- <PlayerFinalScoringAdvancement playerStatus={playerAdvancement} /> -->
				</div>
			{/each}
			<div class="tile" style:width={`${height * TILE_WIDTH_TO_HEIGHT_RATIO}px`}>
				<img class="fill-parent" src={assetUrl(`Boards/FinalScoring/${finalScoringTileNames.get(scoring.tileId)}.png`)} alt="" />
			</div>
		</div>
	</div>
</div>

<style>
	.final-scoring-track {
		width: 100%;
	}

	.wrapper {
		display: flex;
	}

	.player-scorings {
		flex: 1 1 auto;
	}

	.player-scorings > .player-scoring {
		height: 25%;
	}

	.tile {
		height: 100%;
		flex: 0 0 auto;
		margin-left: auto;
	}
</style>
