// Frontend/ProjectSvelte/src/game-page/mobile/PlayerBoxOrArea.svelte
<script lang="ts">
	import type { PlayerInGameDto } from "$dto/interfaces";
	import PlayerArea from "../game-board/players/PlayerArea.svelte";
	import PlayerBox from "../game-board/players/PlayerBox.svelte";

	export let player: PlayerInGameDto;
	export let index: number;
	export let forcePlayerAreaView = false;

	let showArea = false;

	$: {
		if (forcePlayerAreaView) {
			showArea = true;
		}
	}
</script>

<div on:click|stopPropagation={() => (showArea = !showArea)}>
	{#if showArea}
		<PlayerArea {player} framed={true} />
	{:else}
		<PlayerBox {player} {index} />
	{/if}
</div>

// Frontend/StarGate/src/game-page/mobile-view/PlayerBoxOrArea.tsx
import { MouseEvent, useState } from "react";
import { PlayerInGameDto } from "../../dto/interfaces";
import PlayerArea from "../game-board/player-area/PlayerArea";
import PlayerBox from "../game-board/player-box/PlayerBox";

interface PlayerBoxOrAreaProps {
	player: PlayerInGameDto;
	index: number;
}

const PlayerBoxOrArea = ({ player, index }: PlayerBoxOrAreaProps) => {
	const [showArea, setShowArea] = useState(false);
	const toggleView = (evt: MouseEvent<HTMLDivElement>) => {
		evt.stopPropagation();
		setShowArea(!showArea);
	};

	return <div onClick={toggleView}>{showArea ? <PlayerArea player={player} framed={true} /> : <PlayerBox player={player} index={index} />}</div>;
};

export default PlayerBoxOrArea;
